### ISSUE TITLE
SnowBoard not showing up in settings 

### ISSUE THREAD

**Issue by alakhmed** [SparkDev97/SnowBoardTV-Simulator#1]
Hi, 
The real iOS version of SnowBoard that I installed through Cydia is not showing up in settings.
Jailbroken with Undecimus (unc0ver) 
iPhone 5s GSM (iPhone 6,1)
iOS 12.4.8

**Comment by SparkDev97** [comment]
This is not related to SnowBoardTV.
This is also not an issue with SnowBoard - either you have tweaks disabled, or you don't have preferenceloader installed for whatever reason.

For further support, I recommend the r/jailbreak discord server.

**Comment by alakhmed** [comment]
Never mind, I re-jailbreaked and everything came back to normal
